template:
  image: slidewiki/microservicetemplate
  restart: on-failure:5
  expose:
    - "80"
  external_links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
#     - DATABASE_URL=mongodb # use a url or the name, defined in the docker-compose file, not needed here, because of docker-compose v1
    - VIRTUAL_HOST=microservicetemplate.experimental.slidewiki.org
