app:
  build: ./
#  restart: always
  ports:
    - "3000:80"
  links:
    - database:mongodb
  environment:
    - APPLICATION_PORT=80

# Default Mongo Port: 27017
database:
  build: ./mongodb/
#  restart: always
#  mem_limit: 1G
#  volumes:
# Save Database to HOST Filesystem
#    - ./mongodb/database:/data/db:rw
